Repository WIPACrepo/rest-tools, pull requests merged in 2023-02, with the labels that each got.

#101 add a handler mixin for openid auth user detection
  rest_tools/server/__init__.py
  rest_tools/server/handler.py
  tests/unit_server/rest_handler_test.py
Labels: enhancement

#102 allow method to return non-awaitable in decorators
  requirements-dev.txt
  requirements-telemetry.txt
  requirements-tests.txt
  requirements.txt
  rest_tools/server/decorators.py
Labels: bug

#103 add SavedDeviceGrantAuth
  requirements-dev.txt
  requirements-telemetry.txt
  requirements-tests.txt
  requirements.txt
  rest_tools/client/__init__.py
  rest_tools/client/device_client.py
  tests/unit_client/device_client_test.py
Labels: enhancement

#105 allow OpenIDWebHandlerMixin to decode byte or str for the access token
  requirements-dev.txt
  requirements-telemetry.txt
  requirements-tests.txt
  requirements.txt
  rest_tools/server/handler.py
  rest_tools/utils/auth.py
  tests/unit_server/rest_handler_test.py
Labels: bug

#106 work around previous .well-known discovery failures
  rest_tools/client/client_credentials.py
  rest_tools/client/device_client.py
  rest_tools/client/openid_client.py
Labels: bug

#108 CI Updates
  .github/dependabot.yml
  requirements-dev.txt
  requirements-telemetry.txt
  requirements-tests.txt
  requirements.txt
Labels: bug, enhancement, github_actions
